# Generated by Django 2.1.5 on 2019-01-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=500)),
                ('thumbnail_image', models.ImageField(upload_to='videos/media/thumbnail_images/')),
                ('video_file', models.FileField(null=True, upload_to='videos', verbose_name='')),
            ],
        ),
    ]
