# Generated by Django 2.1.5 on 2019-01-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(null=True, upload_to='videos/media/videos', verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/media/videos', verbose_name=''),
        ),
    ]
