# Generated by Django 2.1.5 on 2019-01-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoTutorials',
            new_name='VideoTutorial',
        ),
    ]
