# Generated by Django 2.1.5 on 2019-01-18 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190118_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoLessons',
        ),
    ]
