# Generated by Django 2.1.5 on 2019-01-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190115_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
