# Generated by Django 2.1.5 on 2019-01-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_delete_videolessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotutorial',
            name='thumbnail_image',
            field=models.ImageField(upload_to='media/thumbnail_images/'),
        ),
    ]
