# Generated by Django 2.1.5 on 2019-01-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_delete_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotutorial',
            name='thumbnail_image',
            field=models.ImageField(upload_to='videos/static/thumbnail_images/'),
        ),
    ]
