# Generated by Django 2.1.5 on 2019-01-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20190118_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotutorial',
            name='thumbnail_image',
            field=models.ImageField(upload_to='videos/media/thumbnail_images/'),
        ),
    ]
