# Generated by Django 2.1.5 on 2019-01-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20190117_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotutorial',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='thumbnail_image',
            field=models.ImageField(upload_to='videos/media/thumbnail_images/'),
        ),
    ]
