version: '3.7'
services:
  web-dev:
    build:
      context: .
      dockerfile: docker/development/python/Dockerfile.dev
    command: python /app/manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - static_files:/static_files
      - media_volume:/app/media
    ports:
      - 2000:8000
    expose:
      - 8000
    environment:
      - SECRET_KEY=please_change_me
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:10.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
  static_files:
  media_volume:
