version: '3.7'
services:
  python:
    build:
      context: .
      dockerfile: docker/production/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=video_service.settings.prod
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - static_files:/static_files
      - media_volume:/app/media
    ports:
      - 8000:8000
    command: gunicorn -w 4 video_service.wsgi -b 0.0.0.0:8000
  postgres:
    image: postgres:10.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    build:
      context: .
      dockerfile: docker/production/nginx/Dockerfile
    volumes:
      - static_files:/static_files
      - media_volume:/app/media
    ports:
      - 7000:80
  client:
    build:
      context: .
      dockerfile: docker/production/nodejs/Dockerfile
    volumes:
      - /app/node_modules
      - .:/app


volumes:
  pgdata:
  static_files:
  media_volume: