version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: docker/development/python/Dockerfile.dev
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - static_files:/static_files
      - media_volume:/app/media
    ports:
      - 2000:8000
    expose:
      - 8000
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:10.3
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  static_files:
  media_volume:
