# Pull base image
FROM python:3.7-slim

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
RUN pip install pipenv
COPY ./Pipfile /app/Pipfile
RUN pipenv install --system --skip-lock
RUN pip install psycopg2-binary

#copy entrypoint.sh
COPY ./entrypoint.sh /app/entrypoint.sh

# Copy project
COPY . /app/

# run entrypoint.sh
RUN ["chmod", "+x", "/app/entrypoint.sh"]
