# Generated by Django 2.0.13 on 2019-02-23 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail_image',
            field=models.ImageField(upload_to='media_files/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file_path',
            field=models.FileField(upload_to='media_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov', 'avi', 'flv', 'mpg', 'wmv'])]),
        ),
    ]
