# Generated by Django 2.0.13 on 2019-02-24 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190223_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail_image',
            field=models.ImageField(upload_to='thumbnail_images/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file_path',
            field=models.FileField(upload_to='video_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov', 'avi', 'flv', 'mpg', 'wmv'])]),
        ),
    ]
