# Generated by Django 2.1.5 on 2019-01-26 00:40

from django.db import migrations, models
import video_service.storange_backends


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190123_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(null=True, storage=video_service.storange_backends.PublicMediaStorage(), upload_to='', verbose_name=''),
        ),
    ]
