# Generated by Django 2.1.5 on 2019-01-22 02:28

from django.db import migrations, models
import video_dockerized.storange_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=video_dockerized.storange_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UploadPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=video_dockerized.storange_backends.PrivateMediaStorage(), upload_to='')),
            ],
        ),
    ]
