# Pull base image
FROM python:3.7-slim

#Copy current directory
COPY . /app/

#set current directory
WORKDIR /app

#Run dependacies
RUN pip install --upgrade pip
RUN pip install -r requirements/dev.txt

COPY ./docker/development/python/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]